image: maven:3.8.3-openjdk-17 

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn compile

# This where the magic happens
test:
  stage: test
  script:
    - mvn clean test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/*.xml
    reports:
      junit:
        - target/surefire-reports/*.xml


